version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    container_name: next_blog_frontend_stable
    image: nayanbiswas/next_blog_frontend:stable
    command: ["yarn", "start"]
    env_file: .env
    ports:
      - 5000:3000
    expose:
      - 5000
