export const API_STATE = {
  LOADING: 'LOADING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
};

export const EXCEPTION_TYPE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNHANDLED_ERROR: 'UNHANDLED_ERROR',
  OBJECT_NOT_FOUND: 'OBJECT_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  PERMISSION_ERROR: 'PERMISSION_ERROR',
};
